### PR TITLE
Add KAS

### PR DESCRIPTION
**Pull request by dhardy**
Some improvisation of tags here, since there is little structure.

### CODE REVIEW

**Comment by pythoneer** [comment]
Thanks for your PR! Yeah, we need to go over the tags – it was hard to come up with something as the ecosystem was constantly changing. Looks like it settles it bit and we can reiterate and can come up with something more reasonable.

**Comment by dhardy** [comment]
This still isn't visible. Does it need a manual update?

**Comment by dxenonb** [comment]
@dhardy I'll get on this shortly. Thanks for checking back. The static pages need to be rebuilt. The CLI is giving me an error, though. I hope to investigate it today/tomorrow. (Hopefully I can also get this to happen with github actions. 🤞 )

**Comment by dxenonb** [comment]
@dhardy the error has been resolved and the site updated - let us know if you see any other issues!

**Pull request merged**
