### PR TITLE
Move to Zola for site generation

### PR DESCRIPTION
**Pull request by madsmtm**
Using a well-known project like [Zola](https://www.getzola.org/) for site generation makes it easier for others to contribute, means we have less code to maintain, and should allow us to more easily change things around (e.g. if we want to make the tags be more like categories https://github.com/areweguiyet/areweguiyet/issues/21).

Speaking of tags, I opted to make each a "page" by itself, to make it more strict as to which tags are supported (instead of just allowing any string that the user puts in `tags`).

### CODE REVIEW

**Comment by dxenonb** [comment]
I'll try and test this ASAP!

1) Does this iteration remove all the crates from the homepage? (my concern is: we should finish reviewing the tags before changing the site map, to make sure good crates are not hidden)

2) For hosting a dev/beta site somewhere, does Github Pages work on forks? If/when we make drastic changes, it would be good if we could have a link to share, and run the changes by some other community members/crate authors.

**Comment by madsmtm** [comment]
I think things should look almost the same as before, I haven't yet changed the tag system, only prepared for doing so

**Comment by madsmtm** [comment]
Ok I'm sorry, I tried doing that, and in the process accidentally pushed the contents on this branch to the `master` branch in the repository instead :/

So... If you want to see the result, I guess you just go to https://areweguiyet.com/ ...

**Comment by madsmtm** [comment]
I did end up setting up https://madsmtm.github.io/areweguiyet/, so it should be possible to do so more safely next time.

**Comment by madsmtm** [comment]
I'd still appreciate a review, I'll implement any changes you suggest in a new PR

**Comment by dxenonb** [comment]
No worries. Reviewed and tested - looks good to me.

(Only thing to fix: there is now "List abc" in the title (browser tab) of the home/index page)

I also enabled the branch protection rule, so none of us should be able to push to master now without a PR! Apologies that that wasn't enabled previously.

**Comment by madsmtm** [comment]
> there is now "List abc" in the title (browser tab) of the home/index page

Thanks, I've fixed that in https://github.com/areweguiyet/areweguiyet/pull/120

> I also enabled the branch protection rule

Wonderful!

**Pull request merged**
