### PR TITLE
slint: include link to crates.io

### PR DESCRIPTION
**Pull request by tronical**
The repo tag is automatically picked up from crates.io

### CODE REVIEW

**Comment by blandger** [comment]
It would be fair to mention that it's a commertial product, imho.

**Comment by tronical** [comment]
Sure, could do that. As a sentence in the description? Like "Triple-licensed: GPLv3, Royalty-free, and Commercial" or so?

**Comment by dxenonb** [comment]
@madsmtm what do you think regarding the description?

This may be a good thing to flag as part of #119. (but also... maybe it is "unfair" to put some proprietary icon/etc on the crate when there is an OSS license option)

I'd wait for madsmtm's opinion. If we do agree to update the description, this looks good to me:

> Triple-licensed: GPLv3, Royalty-free, and Commercial

**Comment by madsmtm** [comment]
I don't think we should really deal with the licensing issue, mostly 'cause I think Slint is fine, and if people care about it, then they already have other tools in place to check that their crates have proper licenses (e.g. `cargo deny`).

**Comment by madsmtm** [comment]
Thanks @tronical!

**Pull request merged**
