### PR TITLE
feat: Add Freya

### PR DESCRIPTION
**Pull request by marc2332**
hi 👋 

This adds [Freya](https://github.com/marc2332/freya), a native GUI lib powered by Dioxus and Skia.

Thanks 👍

### CODE REVIEW

**Comment by temeddix** [comment]
Hello @dxenonb @shivshank can new PRs be merged?

**Comment by alexanderkjall** [comment]
@temeddix I'm just a person that sent a PR, I don't have any power to merge PR's :)

**Comment by temeddix** [comment]
I see. Thank you for your response :D

**Comment by madsmtm** [comment]
@dxenonb, do you have permissions to set up the repo such that actions are automatically run for new contributors?

Should be under https://github.com/areweguiyet/areweguiyet/settings/actions, the "Fork pull request workflows from outside collaborators".

**Comment by madsmtm** [comment]
Thanks @marc2332!

**Pull request merged**
