### PR TITLE
Add Floem

### PR DESCRIPTION
**Pull request by pieterdd**

### CODE REVIEW

**Comment by madsmtm** [comment]
Hmm, I'm not really sure I want to add a crate that isn't published to crates.io yet?

**Comment by pieterdd** [comment]
Fair enough. It looks promising though. I took its examples for a ride and even found an element inspector:

floem

Code editor Lapce is already based on it:

Lapce

Closing this PR for now, but definitely one to keep an eye on.

**Comment by Zoxc** [comment]
Xilem is on the list though, which is also unpublished?

**Comment by madsmtm** [comment]
Yeah, good point

**Pull request merged**
